name: Run Selenium C# Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the solution
      run: dotnet build --configuration Release

    - name: Install Playwright browsers
      run: pwsh bin/Debug/net9.0/playwright.ps1 install

    - name: Run tests
      run: dotnet test --configuration Release --no-build --logger "html;LogFileName=TestResults.html"

    - name: Publish test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: '**/TestResults/*.html'